CUDA_VISIBLE_DEVICES=0 python scripts/dino_v2_segvlad_CVGL.py \
    --prog.cache-dir .cache \
    --exp-id cvgl_segvlad_run \
    --task-mode cvgl \
    --cvgl-dataset-root data/Turkey_earthquake_2023_1_336_intile \
    --data-split test \
    --model-type dinov2_vitg14 \
    --num-clusters 32 \
    --desc-layer 31 \
    --desc-facet key \
    --coarse-top-k 10 \
    --tile-size-px 512 \
    --use-local-rerank \
    --local-match-method sim_map \
    --use-offset-head \
    --offset-prediction-method sim_map